{% set name = "cmake-no-system" %}
{% set version = "4.3.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/cmake-{{ version }}.tar.gz
    sha256: b0231eb39b3c3cabdc568c619df78208a7bd95ea10c9b2236d61218bac1b367d
    folder: cmake
  # build cmake with itself on Windows
  - url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/cmake-{{ version }}-windows-x86_64.zip  # [win and x86_64]
    sha256: 83d20c23f5c5f64b3b328785e35b23c532e33057a97ed6294acaca3781b78a01  # [win and x86_64]
    folder: cmake-bin  # [win and x86_64]
  - url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/cmake-{{ version }}-windows-arm64.zip  # [win and arm64]
    sha256: 42a2a88fc57e70d04a92f6eaaac2094241995f53584bc2afdae7e6ef982b3781  # [win and arm64]
    folder: cmake-bin  # [win and arm64]

build:
  number: 1
  skip: True  # [win and vc<14]
  detect_binary_files_with_prefix: False
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ posix }}make
    - jom  # [win]

test:
  commands:
    - cmake --version
    - ctest --version
    - cpack --version

about:
  home: https://cmake.org
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - cmake/LICENSE.rst
    - cmake/Utilities/cmbzip2/LICENSE
    - cmake/Utilities/cmcurl/COPYING
    - cmake/Utilities/cmexpat/COPYING
    - cmake/Utilities/cmjsoncpp/LICENSE
    - cmake/Utilities/cmlibarchive/COPYING
    - cmake/Utilities/cmliblzma/COPYING
    - cmake/Utilities/cmlibrhash/COPYING
    - cmake/Utilities/cmlibuv/LICENSE
    - cmake/Utilities/cmzlib/Copyright.txt
    - cmake/Utilities/cmzstd/LICENSE
  summary: CMake built without system libraries for use when building CMake dependencies.
  description: |
    CMake is an open-source, cross-platform family of tools designed to build, test and package software.
    CMake is used to control the software compilation process using simple platform and compiler independent configuration files,
    and generate native makefiles and workspaces that can be used in the compiler environment of your choice.
  doc_url: https://cmake.org/documentation
  dev_url: https://gitlab.kitware.com/cmake/cmake


extra:
  recipe-maintainers:
    - jjhelmus
    - beckermr
    - xhochy
