{% set version = "3.16.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: cmake-no-system
  version: {{ version }}

source:
  - url: https://gitlab.kitware.com/cmake/cmake/-/archive/v{{ version }}/cmake-v{{ version }}.tar.bz2
    sha256: b716b28ac5a4dbaac332de74766a036d5c8418d1ca559e864984d84e0779ee88
    patches:
      - patches/3.16.2/0001-find_-Add-debug-logging-infrastructure.patch
      - patches/3.16.2/0002-find_-Use-debug-logging-infrastructure.patch
      - patches/3.16.2/0003-Add-more-debug-logging-to-cmFindCommon.patch
    folder: cmake

  # build cmake with itself on Windows
  - url: https://cmake.org/files/v{{ version[:4] }}/cmake-{{ version }}-win32-x86.zip  # [win32]
    sha256: 9110d3c68377f4dd21105414f6d2cea434959252d8e1a20fc29da3978f6f31de  # [win32]
    folder: cmake-bin  # [win32]

  - url: https://cmake.org/files/v{{ version[:4] }}/cmake-{{ version }}-win64-x64.zip  # [win64]
    sha256: 70812d07a19d4e14a9e625fdd698f0dcd0c6f32d81d63979c645f5327e0772e2  # [win64]
    folder: cmake-bin  # [win64]

build:
  number: 3
  skip: True  # [win and vc<14]
  detect_binary_files_with_prefix: False
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ posix }}make
    - {{ posix }}patch
    - jom             # [win]

test:
  commands:
    - cmake --version
    - ctest --version
    - cpack --version

about:
  home: http://www.cmake.org/
  doc_url: http://cmake.org/documentation/
  dev_url: http://gitlab.kitware.com/cmake/cmake
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - cmake/Copyright.txt
    - cmake/Utilities/cmbzip2/LICENSE
    - cmake/Utilities/cmcurl/COPYING
    - cmake/Utilities/cmexpat/COPYING
    - cmake/Utilities/cmjsoncpp/LICENSE
    - cmake/Utilities/cmlibarchive/COPYING
    - cmake/Utilities/cmliblzma/COPYING
    - cmake/Utilities/cmlibrhash/COPYING
    - cmake/Utilities/cmlibuv/LICENSE
    - cmake/Utilities/cmzlib/Copyright.txt
    - cmake/Utilities/cmzstd/LICENSE
  summary: CMake built without system libraries for use when building CMake dependencies.
  description: | 
  CMake is an open-source, cross-platform family of tools designed to build, test and package software. 
  CMake is used to control the software compilation process using simple platform and compiler independent configuration files, 
  and generate native makefiles and workspaces that can be used in the compiler environment of your choice.


extra:
  recipe-maintainers:
    - jjhelmus
    - beckermr
    - xhochy
