{% set version = "3.18.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: cmake-no-system
  version: {{ version }}

source:
  - url: https://gitlab.kitware.com/cmake/cmake/-/archive/v{{ version }}/cmake-v{{ version }}.tar.bz2
    sha256: ac4553222845817975423fd8466872cbeee595cf9c3c63f4217825092882e6d9
    folder: cmake

  # build cmake with itself on Windows
  - url: https://cmake.org/files/v{{ version[:4] }}/cmake-{{ version }}-win64-x64.zip  # [win64]
    sha256: cff2afc0dfe84f96b5078ea779a1556277fa17a93ea7e03cc358831fafa5711e  # [win64]
    folder: cmake-bin  # [win64]

build:
  number: 0
  skip: True  # [win and vc<14]
  detect_binary_files_with_prefix: False
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ posix }}make
    - {{ posix }}patch
    - jom             # [win]

test:
  commands:
    - cmake --version
    - ctest --version
    - cpack --version

about:
  home: http://www.cmake.org/
  doc_url: http://cmake.org/documentation/
  dev_url: http://gitlab.kitware.com/cmake/cmake
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - cmake/Copyright.txt
    - cmake/Utilities/cmbzip2/LICENSE
    - cmake/Utilities/cmcurl/COPYING
    - cmake/Utilities/cmexpat/COPYING
    - cmake/Utilities/cmjsoncpp/LICENSE
    - cmake/Utilities/cmlibarchive/COPYING
    - cmake/Utilities/cmliblzma/COPYING
    - cmake/Utilities/cmlibrhash/COPYING
    - cmake/Utilities/cmlibuv/LICENSE
    - cmake/Utilities/cmzlib/Copyright.txt
    - cmake/Utilities/cmzstd/LICENSE
  summary: CMake built without system libraries for use when building CMake dependencies.
  
  description: |
    CMake is an open-source, cross-platform family of tools designed to build, test and package software.
    CMake is used to control the software compilation process using simple platform and compiler independent configuration files,
    and generate native makefiles and workspaces that can be used in the compiler environment of your choice.


extra:
  recipe-maintainers:
    - jjhelmus
    - beckermr
    - xhochy
