{% set version = "3.25.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: cmake-no-system
  version: {{ version }}

source:

  - url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/cmake-{{ version }}.tar.gz
    sha256: cc995701d590ca6debc4245e9989939099ca52827dd46b5d3592f093afe1901c
    folder: cmake
  - url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/cmake-{{ version }}-windows-x86_64.zip  # [win and x86_64]
    sha256: 109c29a744d648863d3637b4963c90088045c8d92799c68c9b9d8713407776c8  # [win and x86_64]
    folder: cmake-bin  # [win and x86_64]
  - url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/cmake-{{ version }}-windows-arm64.zip  # [win and arm64]
    sha256: 3498fea26257eebfbfc89ed17963f3d8d83c19362b90fb23517842de777a522a  # [win and arm64]
    folder: cmake-bin  # [win and arm64]

build:
  number: 0
  skip: True  # [win and vc<14]
  detect_binary_files_with_prefix: False
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ posix }}make
    - jom             # [win]

test:
  commands:
    - cmake --version
    - ctest --version
    - cpack --version

about:
  home: https://cmake.org/
  doc_url: https://cmake.org/documentation/
  dev_url: https://gitlab.kitware.com/cmake/cmake
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - cmake/Copyright.txt
    - cmake/Utilities/cmbzip2/LICENSE
    - cmake/Utilities/cmcurl/COPYING
    - cmake/Utilities/cmexpat/COPYING
    - cmake/Utilities/cmjsoncpp/LICENSE
    - cmake/Utilities/cmlibarchive/COPYING
    - cmake/Utilities/cmliblzma/COPYING
    - cmake/Utilities/cmlibrhash/COPYING
    - cmake/Utilities/cmlibuv/LICENSE
    - cmake/Utilities/cmzlib/Copyright.txt
    - cmake/Utilities/cmzstd/LICENSE
  summary: CMake built without system libraries for use when building CMake dependencies.
  
  description: |
    CMake is an open-source, cross-platform family of tools designed to build, test and package software.
    CMake is used to control the software compilation process using simple platform and compiler independent configuration files,
    and generate native makefiles and workspaces that can be used in the compiler environment of your choice.


extra:
  recipe-maintainers:
    - jjhelmus
    - beckermr
    - xhochy
